### ISSUE TITLE
External server

### ISSUE THREAD

**Issue by ghost** [Studentmediene/Barteguiden-iOS#1]
Create the database for the external server. PHP?

**Comment by magnuskiro** [comment]
PHP is not a database. HSQL,  MySQL and PostgreSQL are database implementations. What you'r thinking about is probably a service that handles the data. And for that Java is nice. 

Look at this for some starting help.
http://blog.springsource.org/2011/02/10/getting-started-with-spring-data-jpa/
This post describes use of SpringDataJPA nicely. 
Look at this repository on google for eksamples of how to use SpringDataJPA https://github.com/magnuskiro/kiroweb
